version: "3.9"

services:
  ml-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: real-time-ml-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped

